[package]
name = "assignmnet_comsec"
version = "0.1.0"
edition = "2021"

[dependencies]

rcgen = "0.13.2"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

